spring:
  thymeleaf:
    mode: LEGACYHTML5

  datasource:
    url: jdbc:h2:mem:AZ;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
    driverClassName: org.h2.Driver
    username: sa
  jpa:
    show-sql: true
    properties:
      hibernate:
        show_sql: true
        format_sql: true
        current_session_context_class: org.springframework.orm.hibernate4.SpringSessionContext
    hibernate:
        implicit-strategy: org.hibernate.cfg.ImprovedNamingStrategy

logging:
  level:
    org:
      hibernate:
        type: trace


pass:
  size: 4
